### ISSUE TITLE
Connection fails at login

### ISSUE THREAD

**Issue by MPocke** [p0l0/hagruenbeck_cloud#152]
### System Health details

Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

In the configuration process of the integration, I run into a connection error after entering the login data.
The integration was downloaded via HACS and the Home Assistant was then restarted. The login data was checked several times. The error message is “Connection failed”.

### Reproduction steps

1. Download Integration via HACS
2. Restart Home Assistant
3. Configure Integration --> Add login Data "save"

### Debug logs

```text
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.gruenbeck_cloud.config_flow
Quelle: custom_components/gruenbeck_cloud/config_flow.py:141
Integration: Grünbeck Cloud (Dokumentation, Probleme)
Erstmals aufgetreten: 07:39:02 (4 Vorkommnisse)
Zuletzt protokolliert: 07:56:18

'has_error'
```

**Comment by p0l0** [comment]
Which device do you have?

**Comment by MPocke** [comment]
You mean the Grünbeck Device? It's a Grünbeck SC18

**Comment by p0l0** [comment]
This integration only supports SD and SE models, which are Cloud only.

SC models use a local API, there seems to be an integration for that models, please look at this [comment](https://github.com/p0l0/hagruenbeck_cloud/issues/12#issuecomment-2391997785)
