### ISSUE TITLE
daily consumption as a sensor

### ISSUE THREAD

**Issue by Schneeschuher** [p0l0/hagruenbeck_cloud#57]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

How do i get the daily water consumption. 
It is shown in the energy dashboard but i would like to use it as a sensor.
Any ideas?

### Describe the solution you'd like

daily consumption as a sensor

### Describe alternatives you've considered

no alternatives

### Additional context

no additional context

**Comment by p0l0** [comment]
You already have it as a sensor. That what you created is a template sensor, which you can normally use.

The created Sensor would be: ```sensor.<name_of_the_sensor>``` in the README example _"Total Water Usage"_ would be ```sensor.total_water_usage```.
