### ISSUE TITLE
Make attribute error message more readable

### ISSUE THREAD

**Issue by fugazzy** [p0l0/hagruenbeck_cloud#66]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Currently I cannot display the error message in a tile card as attribute as the text is too long.

### Describe the solution you'd like

I would love to see just the message without "message:" in the front (message: Wartung fällig  ---> Wartung fällig)

### Describe alternatives you've considered

extra template sensor should not be necessary.

### Additional context

none

**Comment by p0l0** [comment]
I just checked the implementation, and there is no ``message`` before, it's the key for the object.

If you use this template:

```jinja2
Current errors:
{% for error in state_attr('binary_sensor.softliq_d_kd8394323_has_error', 'errors') %}
  ======
  Is error resolved? {{error.isResolved}}
  Message is: {{error.message}}
  Type of error: {{error.type}}
  Date of error: {{error.date}}
{% endfor %}
```

You will get something like this:

```
Current errors:

  ======
  Is error resolved? True
  Message is: Salt supply used up!
  Type of error: error
  Date of error: 2023-02-20T17:20:36.609000

  ======
  Is error resolved? True
  Message is: Maintenance due!
  Type of error: warning
  Date of error: 2023-01-03T14:35:24.655000

  ======
  Is error resolved? True
  Message is: Maintenance due!
  Type of error: warning
  Date of error: 2022-01-02T11:23:12.819000
```
