### ISSUE TITLE
Login not working - has error

### ISSUE THREAD

**Issue by adieball** [p0l0/hagruenbeck_cloud#73]
## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4988
Installed Version | 1.34.0
Stage | running
Available Repositories | 1400
Downloaded Repositories | 13
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 10. Juni 2024 um 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-20.ui.nabu.casa
certificate_status | ready
instance_id | 1a6e71a0290548809eae314e5f3377d8
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 6.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), File editor (5.8.0), Mosquitto broker (6.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19. Mai 2024 um 06:43
-- | --
current_recorder_run | 25. Mai 2024 um 13:56
estimated_db_size | 381.34 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After logging in I get the following in the logfile:

Logger: custom_components.gruenbeck_cloud.config_flow
Quelle: custom_components/gruenbeck_cloud/config_flow.py:141
Integration: Grünbeck Cloud ([Dokumentation](https://github.com/p0l0/hagruenbeck_cloud), [Probleme](https://github.com/p0l0/hagruenbeck_cloud/issues))
Erstmals aufgetreten: 14:22:51 (3 Vorkommnisse)
Zuletzt protokolliert: 14:37:54

'has_error'

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
.
```

### Diagnostics dump

.

**Comment by p0l0** [comment]
Which model do you have? Seems to be the same as #12
