### ISSUE TITLE
Green ring is always on

### ISSUE THREAD

**Issue by renekar** [p0l0/hagruenbeck_cloud#84]
### System Health details

Since I’ve installed the addon in HA, the green ring is always on. Before, and confirmed by settings at the Grünbeck, led is only on while consuming water or touching the interface

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Green ring is always on.

### Reproduction steps

Without addon, led is on only at water consumption or touching the interface on the device.

### Debug logs

```text
-
```

**Comment by lewurm** [comment]
Why was this closed?

I'm observing the same issue.  Any idea how to fix that?
