### ISSUE TITLE
Stop after "Task exception"

### ISSUE THREAD

**Issue by derjoerg** [p0l0/hagruenbeck_cloud#9]
## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.33.0
Stage | running
Available Repositories | 1458
Downloaded Repositories | 65
HACS Data | ok

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 16. September 2024 um 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
instance_id | a7fe12d5565c4109a7dc2704cdd5220b
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Discovergy</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 48.5 GB
disk_used | 32.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.4), Samba share (12.2.0), Mosquitto broker (6.4.0), Node-RED (17.0.3), Samba Backup (5.2.0), File editor (5.7.0), ioBroker (0.8.0), ESPHome (2023.12.5), Signal Messenger (0.80.0), Matter Server (5.0.3), Music Assistant BETA (2.0.0b82), Speedtest (1.5.0), Piper (1.4.0), Whisper (1.0.2), Studio Code Server (5.15.0), PSA Car Controller (v3.3.2), MQTT Explorer (browser-1.0.3), openWakeWord (1.8.2), NGINX Home Assistant SSL proxy (3.7.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 38
views | 56
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9. Januar 2024 um 19:03
-- | --
current_recorder_run | 19. Januar 2024 um 09:15
estimated_db_size | 5704.94 MiB
database_engine | mysql
database_version | 10.11.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I sometimes get the below mentioned error and then the integration is not useable anymore, no updates anymore. I need to reload the integration to receive data.

### Reproduction steps

1. I don't know

### Debug logs

```text
Logger: homeassistant
Source: custom_components/gruenbeck_cloud/coordinator.py:66
Integration: Grünbeck Cloud (documentation, issues)
First occurred: 09:52:58 (1 occurrences)
Last logged: 09:52:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/gruenbeck_cloud/coordinator.py", line 66, in listen
    await self.api.listen(callback=self.async_set_updated_data)
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 780, in listen
    await self.refresh_sd()
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 599, in refresh_sd
    await self._http_request(
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 680, in _http_request
    raise PyGruenbeckCloudResponseStatusError(error)
pygruenbeck_cloud.exceptions.PyGruenbeckCloudResponseStatusError: Response status code for https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices/softliQ.D/BS40008472/realtime/refresh?api-version=2020-08-03 is 500, we expected 202.
```

**Comment by gomble** [comment]
Same

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/gruenbeck_cloud/coordinator.py:66
Integration: Grünbeck Cloud (documentation, issues)
First occurred: 16:00:25 (1 occurrences)
Last logged: 16:00:25

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/gruenbeck_cloud/coordinator.py", line 66, in listen
    await self.api.listen(callback=self.async_set_updated_data)
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 780, in listen
    await self.refresh_sd()
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 599, in refresh_sd
    await self._http_request(
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 680, in _http_request
    raise PyGruenbeckCloudResponseStatusError(error)
pygruenbeck_cloud.exceptions.PyGruenbeckCloudResponseStatusError: Response status code for https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices/softliQ.D/BS50020597/realtime/refresh?api-version=2020-08-03 is 500, we expected 202.
`

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.gruenbeck_cloud.coordinator
Source: custom_components/gruenbeck_cloud/coordinator.py:66
Integration: Grünbeck Cloud (documentation, issues)
First occurred: 16:00:25 (1 occurrences)
Last logged: 16:00:25

Response status code for https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices/softliQ.D/BS50020597/realtime/refresh?api-version=2020-08-03 is 500, we expected 202.`
